[export.summary.default]
branchNameLineEdit = ""
pathLineEdit = ""
fileNameLineEdit = ""
noActionRadioButton = true
openFolderRadioButton = false
openFileRadioButton = false
useLastOptionsCheckbox = false
saveLastOpeningBalanceCheckbox = false
openingBalanceSpinbox = 0.0

[export.summary.user]
branchNameLineEdit = ""
pathLineEdit = ""
fileNameLineEdit = ""
noActionRadioButton = true
openFolderRadioButton = false
openFileRadioButton = false
useLastOptionsCheckbox = false
saveLastOpeningBalanceCheckbox = false
openingBalanceSpinbox = 0.0

[export.transactions.default]
branchNameLineEdit = ""
pathLineEdit = ""
fileNameLineEdit = ""
noActionRadioButton = true
openFolderRadioButton = false
openFileRadioButton = false
useLastOptionsCheckbox = false

[export.transactions.user]
branchNameLineEdit = ""
pathLineEdit = ""
fileNameLineEdit = ""
noActionRadioButton = true
openFolderRadioButton = false
openFileRadioButton = false
useLastOptionsCheckbox = false

[tools.cash_balance_values.default]

[tools.cash_balance_values.user]