[export.default]
branchNameLineEdit = ""
pathLineEdit = ""
fileNameLineEdit = ""
noActionRadioButton = true
openFolderRadioButton = false
openFileRadioButton = false
useLastOptionsCheckbox = true
saveLastOpeningBalanceCheckbox = false
openingBalanceSpinbox = 0.0

[export.user]
branchNameLineEdit = ""
pathLineEdit = ""
fileNameLineEdit = ""
noActionRadioButton = true
openFolderRadioButton = false
openFileRadioButton = false
useLastOptionsCheckbox = true
saveLastOpeningBalanceCheckbox = false
openingBalanceSpinbox = 0.0