from pathlib import Path

REQUIRED_CONFIG_FILES = [
    Path("config") / "settings.toml",
]

REQUIRED_JSON_FILES = [
    Path("cs_CZ") / "ui_texts.json",
    Path("en_GB") / "ui_texts.json",
    Path("cs_CZ") / "error_texts.json",
    Path("en_GB") / "error_texts.json",
    Path("cs_CZ") / "headers_texts.json",
    Path("en_GB") / "headers_texts.json",
    Path("cs_CZ") / "confirm_texts.json",
    Path("en_GB") / "confirm_texts.json",
    Path("cs_CZ") / "notification_texts.json",
    Path("en_GB") / "notification_texts.json",
    Path("cs_CZ") / "status_texts.json",
    Path("en_GB") / "status_texts.json",
    Path("cs_CZ") / "export_texts.json",
    Path("en_GB") / "export_texts.json",
]

REQUIRED_IMAGES = [
    Path("system") / "SplashScreen.jpg",
    Path("ui_icons") / "activeIcon.png",
    Path("ui_icons") / "inactiveIcon.png",
]

UI_KEYS = [
    ("MainWindow", "titleText"),
    ("SidePanel", "transactionsButtonText"),
    ("SidePanel", "transactionsButtonTooltipText"),
    ("SidePanel", "customersButtonText"),
    ("SidePanel", "customersButtonTooltipText"),
    ("SidePanel", "exportButtonText"),
    ("SidePanel", "exportButtonTooltipText"),
    ("SidePanel", "catalogButtonText"),
    ("SidePanel", "catalogButtonTooltipText"),
    ("SidePanel", "inventoryButtonText"),
    ("SidePanel", "inventoryButtonTooltipText"),
    ("SidePanel", "settingsButtonText"),
    ("SidePanel", "settingsButtonTooltipText"),
    ("TransactionsWidget", "itemsCountLabelText"),
    ("TransactionsWidget", "priceSuffix"),
    ("TransactionsView", "updateTransactionActionText"),
    ("TransactionsView", "deleteTransactionActionText"),
    ("TransactionsActionsWidget", "inTransactionButtonText"),
    ("TransactionsActionsWidget", "inTransactionButtonTooltipText"),
    ("TransactionsActionsWidget", "outTransactionButtonText"),
    ("TransactionsActionsWidget", "outTransactionButtonTooltipText"),
    ("TransactionsActionsWidget", "searchLineEditPlaceholderText"),
    ("TransactionsActionsWidget", "baseFilterComboboxItems"),
    ("TransactionsTabWidget", "inTabTitleText"),
    ("TransactionsTabWidget", "outTabTitleText"),
    ("CustomersActionsWidget", "addCustomerButtonText"),
    ("CustomersActionsWidget", "addCustomerButtonTooltipText"),
    ("CustomersActionsWidget", "searchLineEditPlaceholderText"),
    ("CustomersWidget", "countLabelText"),
    ("CustomersView", "updateCustomerActionText"),
    ("CustomersView", "activeCustomerActionText"),
    ("InventoryWidget", "countLabelText"),
    ("InventoryActionsWidget", "searchLineEditPlaceholderText"),
    ("PeriodExportWidget", "pathNameGroupBoxText"),
    ("PeriodExportWidget", "fileTypeLabelText"),
    ("PeriodExportWidget", "fileTypeComboBoxItems"),
    ("PeriodExportWidget", "pathLabelText"),
    ("PeriodExportWidget", "pathButtonText"),
    ("PeriodExportWidget", "folderDialogTitle"),
    ("PeriodExportWidget", "fileNameLabelText"),
    ("PeriodExportWidget", "fileNameLineEditText"),
    ("PeriodExportWidget", "nameLineEditPlaceholderText"),
    ("PeriodExportWidget", "dateOptionsGroupBoxText"),
    ("PeriodExportWidget", "todayRadioButtonText"),
    ("PeriodExportWidget", "weekRadioButtonText"),
    ("PeriodExportWidget", "monthRadioButtonText"),
    ("PeriodExportWidget", "yearRadioButtonText"),
    ("PeriodExportWidget", "customRadioButtonText"),
    ("PeriodExportWidget", "fromDateLabelText"),
    ("PeriodExportWidget", "toDateLabelText"),
    ("PeriodExportWidget", "financialDataGroupBoxText"),
    ("PeriodExportWidget", "priceSuffix"),
    ("PeriodExportWidget", "openingBalanceLabelText"),
    ("PeriodExportWidget", "incomeLabelText"),
    ("PeriodExportWidget", "expenseLabelText"),
    ("PeriodExportWidget", "exportOptionsGroupBoxText"),
    ("PeriodExportWidget", "noActionRadioButtonText"),
    ("PeriodExportWidget", "openFolderRadioButtonText"),
    ("PeriodExportWidget", "openFileRadioButtonText"),
    ("PeriodExportWidget", "exportButtonText"),
    ("PeriodExportWidget", "exportButtonTooltipText"),
    ("ErrorDialog", "closeDialogButtonText"),
    ("ErrorDialog", "closeDialogButtonTooltipText"),
    ("ErrorDialog", "closeAppButtonText"),
    ("ErrorDialog", "closeAppButtonTooltipText"),
    ("CustomerDialog", "titleText"),
    ("CustomerDialog", "createdLabelText"),
    ("CustomerDialog", "subjectTypePlaceholderText"),
    ("CustomerDialog", "subjectTypeItems"),
    ("CustomerDialog", "companyLabelText"),
    ("CustomerDialog", "firstNameLabelText"),
    ("CustomerDialog", "lastNameLabelText"),
    ("CustomerDialog", "documentTypeLabelText"),
    ("CustomerDialog", "addressLabelText"),
    ("CustomerDialog", "activeLabelText"),
    ("CustomerDialog", "notesLabelText"),
    ("CustomerDialog", "notesCountLabelText"),
    ("CustomerDialog", "saveButtonText"),
    ("CustomerDialog", "saveButtonTooltipText"),
    ("CustomerDialog", "closeButtonText"),
    ("CustomerDialog", "closeButtonTooltipText"),
    ("CategoryDialog", "titleText"),
    ("CategoryDialog", "categoryNameLabelText"),
    ("CategoryDialog", "notesLabelText"),
    ("CategoryDialog", "notesCountLabelText"),
    ("CategoryDialog", "saveButtonText"),
    ("CategoryDialog", "saveButtonTooltipText"),
    ("CategoryDialog", "closeButtonText"),
    ("CategoryDialog", "closeButtonTooltipText"),
    ("CommodityDialog", "titleText"),
    ("CommodityDialog", "categoryLabelText"),
    ("CommodityDialog", "nameLabelText"),
    ("CommodityDialog", "unitLabelText"),
    ("CommodityDialog", "unitInputItems"),
    ("CommodityDialog", "warningLabelText"),
    ("CommodityDialog", "defaultPriceLabelText"),
    ("CommodityDialog", "activeLabelText"),
    ("CommodityDialog", "notesLabelText"),
    ("CommodityDialog", "notesCountLabelText"),
    ("CommodityDialog", "saveButtonText"),
    ("CommodityDialog", "saveButtonTooltipText"),
    ("CommodityDialog", "closeButtonText"),
    ("CommodityDialog", "closeButtonTooltipText"),
    ("CatalogWidget", "addCategoryButtonText"),
    ("CatalogWidget", "addCategoryButtonTooltipText"),
    ("CatalogWidget", "catalogTitleLabelText"),
    ("CatalogDefaultWidget", "titleLabelText"),
    ("CatalogDefaultWidget", "subtitleLabelText"),
    ("CategoryDetailWidget", "categoryGroupBoxText"),
    ("CategoryDetailWidget", "notesLabelText"),
    ("CategoryDetailWidget", "updateCategoryButtonText"),
    ("CategoryDetailWidget", "updateCategoryButtonTooltipText"),
    ("CategoryDetailWidget", "addCommodityButtonText"),
    ("CategoryDetailWidget", "addCommodityButtonTooltipText"),
    ("CommoditiesGridWidget", "commoditiesGroupBoxText"),
    ("CommoditiesGridWidget", "noCommoditiesLabelText"),
    ("CommodityCardWidget", "unitLabelText"),
    ("CommodityCardWidget", "defaultPriceLabelText"),
    ("CommodityCardWidget", "activeLabelText"),
    ("CommodityCardWidget", "notesLabelText"),
    ("CommodityCardWidget", "updateCommodityButtonText"),
    ("CommodityCardWidget", "updateCommodityButtonTooltipText"),
    ("CreateTransactionDialog", "titleText"),
    ("CreateTransactionDialog", "paymentTypeLabelText"),
    ("CreateTransactionDialog", "paymentTypeComboboxItems"),
    ("CreateTransactionDialog", "customerNameLabelText"),
    ("CreateTransactionDialog", "customerDocumentNumberLabelText"),
    ("CreateTransactionDialog", "customerAddressLabelText"),
    ("CreateTransactionDialog", "continueTransactionButtonText"),
    ("CreateTransactionDialog", "continueTransactionButtonTooltipText"),
    ("CreateTransactionDialog", "cancelTransactionButtonText"),
    ("CreateTransactionDialog", "cancelTransactionButtonTooltipText"),
    ("TransactionItemsDialogIn", "titleText"),
    ("TransactionItemsDialogIn", "saveTransactionButtonText"),
    ("TransactionItemsDialogIn", "saveTransactionButtonTooltipText"),
    ("TransactionItemsDialogIn", "cancelTransactionButtonText"),
    ("TransactionItemsDialogIn", "cancelTransactionButtonTooltipText"),
    ("TransactionItemsDialogIn", "CASH"),
    ("TransactionItemsDialogIn", "TRANSFER"),
    ("TransactionItemsDialogOut", "titleText"),
    ("TransactionItemsDialogOut", "saveTransactionButtonText"),
    ("TransactionItemsDialogOut", "saveTransactionButtonTooltipText"),
    ("TransactionItemsDialogOut", "cancelTransactionButtonText"),
    ("TransactionItemsDialogOut", "cancelTransactionButtonTooltipText"),
    ("TransactionItemsDialogOut", "CASH"),
    ("TransactionItemsDialogOut", "TRANSFER"),
    ("TransactionInfoWidget", "customerNameLabelText"),
    ("TransactionInfoWidget", "documentNumberLabelText"),
    ("TransactionInfoWidget", "addressLabelText"),
    ("TransactionInfoWidget", "updateTransactionInfoButtonText"),
    ("TransactionInfoWidget", "updateTransactionInfoButtonTooltipText"),
    ("TransactionInfoWidget", "notesCountLabelText"),
    ("TransactionsItemsWidget", "addItemButtonText"),
    ("TransactionsItemsWidget", "addItemButtonTooltipText"),
    ("TransactionsItemsWidget", "updateItemButtonText"),
    ("TransactionsItemsWidget", "updateItemButtonTooltipText"),
    ("TransactionsItemsWidget", "deleteButtonText"),
    ("TransactionsItemsWidget", "deleteButtonTooltipText"),
    ("TransactionsItemsWidget", "totalPriceLabelText"),
    ("TransactionsItemsWidget", "priceSuffix"),
    ("CategoryCommodityDialog", "titleText"),
    ("CategoryCommodityDialog", "categoryLabelText"),
    ("CategoryCommodityDialog", "categoryComboBoxPlaceholderText"),
    ("CategoryCommodityDialog", "commodityLabelText"),
    ("CategoryCommodityDialog", "commodityComboBoxPlaceholderText"),
    ("CategoryCommodityDialog", "unitLabelText"),
    ("CategoryCommodityDialog", "priceLabelText"),
    ("CategoryCommodityDialog", "addButtonText"),
    ("CategoryCommodityDialog", "addButtonTooltipText"),
    ("CategoryCommodityDialog", "cancelButtonText"),
    ("CategoryCommodityDialog", "cancelButtonTooltipText"),
    ("SettingsWidget", "periodExportTabTitle"),
    ("PeriodExportSettings", "branchGroupBoxText"),
    ("PeriodExportSettings", "branchNameLabelText"),
    ("PeriodExportSettings", "branchNameLineEditPlaceholderText"),
    ("PeriodExportSettings", "pathNameGroupBoxText"),
    ("PeriodExportSettings", "pathLabelText"),
    ("PeriodExportSettings", "pathButtonText"),
    ("PeriodExportSettings", "folderDialogTitle"),
    ("PeriodExportSettings", "fileNameLabelText"),
    ("PeriodExportSettings", "fileNameLineEditPlaceholderText"),
    ("PeriodExportSettings", "exportOptionsGroupBoxText"),
    ("PeriodExportSettings", "noActionRadioButtonText"),
    ("PeriodExportSettings", "openFolderRadioButtonText"),
    ("PeriodExportSettings", "openFileRadioButtonText"),
    ("PeriodExportSettings", "otherSettingsGroupBoxText"),
    ("PeriodExportSettings", "useLastOptionsCheckboxText"),
    ("PeriodExportSettings", "saveLastOpeningBalanceCheckboxText"),
    ("PeriodExportSettings", "restoreButtonText"),
    ("PeriodExportSettings", "restoreButtonTooltipText"),
    ("PeriodExportSettings", "saveButtonText"),
    ("PeriodExportSettings", "saveButtonTooltipText"),
]

HEADERS_KEYS = [
    ("CustomersView", "company"),
    ("CustomersView", "document_number"),
    ("CustomersView", "address"),
    ("CustomersView", "active"),
    ("TransactionView", "category"),
    ("TransactionView", "commodity"),
    ("TransactionView", "commodityId"),
    ("TransactionView", "unitCount"),
    ("TransactionView", "pricePerUnit"),
    ("TransactionView", "totalPrice"),
    ("TransactionsView", "headers_texts"),
    ("InventoryView", "0"),
    ("InventoryView", "1"),
    ("InventoryView", "2"),
    ("InventoryView", "3"),
    ("InventoryView", "4"),
]

ERROR_KEYS = [
    "APP_INIT_FAILED",
    "RESOURCES_MISSING",
    "DOWNLOAD_FAILED",
    "TEXTS_LOAD_FAILED",
    "CONFIG_LOAD_FAILED",
    "SETTINGS_FAILED",
    "DATABASE_FAILED",
    "DATABASE_ERROR",
    "EXPORT_ERROR",
    "PATH_ERROR",
    "CRITICAL_FAILURE",
    "UNKNOWN_ERROR",
    "CONNECTION_ERROR",
    "PERMISSION_ERROR",
]

CONFIRM_STRUCTURE = {
    "ACTIVE": ["TITLE", "TEXT", "YES", "NO"],
    "NO_RESULTS": ["TITLE", "TEXT", "CLOSE"],
    "NO_CUSTOMERS": ["TITLE", "TEXT", "CLOSE"],
    "NO_CATEGORY": ["TITLE", "TEXT", "CLOSE"],
    "TREE_ITEM_CREATION_FAILED": ["TITLE", "TEXT", "CLOSE"],
    "NO_DATA": ["TITLE", "TEXT", "CLOSE"],
    "INVALID_DATA": ["TITLE", "TEXT", "CLOSE"],
    "ITEMS_DATA_FAILED": ["TITLE", "TEXT", "CLOSE"],
    "INVALID_COMMODITY_UNIT": ["TITLE", "TEXT", "CLOSE"],
    "ZERO_PRICE_TRANSACTION": ["TITLE", "TEXT", "YES", "NO"],
    "DELETE_TRANSACTION_ITEM": ["TITLE", "TEXT", "YES", "NO"],
    "DATABASE_ERROR": ["TITLE", "TEXT", "CLOSE"],
    "DELETE_TRANSACTION": ["TITLE", "TEXT", "YES", "NO"],
    "RESTORE_SETTINGS": ["TITLE", "TEXT", "YES", "NO"],
    "PATH_EXISTS": ["TITLE", "TEXT", "YES", "NO"],
    "OPEN_FILE_FAILED": ["TITLE", "TEXT", "CLOSE"],
    "OPEN_EXPLORER_FAILED": ["TITLE", "TEXT", "CLOSE"],
}

NOTIFICATION_KEYS = [
    ("CUSTOMERS", "ADD_CUSTOMER"),
    ("CUSTOMERS", "UPDATE_CUSTOMER"),
    ("CUSTOMERS", "CHANGE_ACTIVE"),
    ("CATALOG", "ADD_CATEGORY"),
    ("CATALOG", "UPDATE_CATEGORY"),
    ("CATALOG", "ADD_COMMODITY"),
    ("CATALOG", "UPDATE_COMMODITY"),
    ("TRANSACTIONS", "ADD_TRANSACTION"),
    ("TRANSACTIONS", "UPDATE_TRANSACTION"),
    ("TRANSACTIONS", "DELETE_TRANSACTION"),
    ("EXPORT", "EXPORT_COMPLETED"),
]

STATUS_KEYS = ["SETTINGS_SAVED", "SETTINGS_RESTORED", "READY"]

EXPORT_KEYS = [
    ("ProgressDialog", "loadingDataText"),
    ("ProgressDialog", "exportInProgressText"),
    ("PeriodSheet", "sheetName"),
    ("PeriodSheet", "titleText"),
    ("PeriodSheet", "rangeText"),
    ("PeriodSheet", "branchText"),
    ("PeriodSheet", "notesText"),
    ("PeriodSheet", "financialText"),
    ("PeriodSheet", "openingBalanceText"),
    ("PeriodSheet", "buybackText"),
    ("PeriodSheet", "incomeText"),
    ("PeriodSheet", "expenseText"),
    ("PeriodSheet", "balanceText"),
    ("PeriodSheet", "currencySuffix"),
    ("PeriodSheet", "commodityText"),
    ("PeriodSheet", "pricePerUnitText"),
    ("PeriodSheet", "quantityText"),
    ("PeriodSheet", "totalPriceText"),
    ("PeriodSheet", "summaryPriceText"),
    ("PeriodSheet", "exportText"),
    ("PeriodSheet", "pageText"),
]
