CUSTOMERS_HORIZONTAL_PADDING = 50
INVENTORY_HORIZONTAL_PADDING = 15

ADD_MODE = "ADD"
UPDATE_MODE = "UPDATE"

TRANSFER_IN = "IN"
TRANSFER_OUT = "OUT"

TRANSACTION_INFO_WIDGET_NOTES_LENGTH = 200

CATEGORY_COMMODITY_DIALOG_MIN_VALUE = 0.0
CATEGORY_COMMODITY_DIALOG_MAX_UNIT_VALUE = 99_999_999.9
CATEGORY_COMMODITY_DIALOG_MAX_PRICE_VALUE = 1_000.0

CATEGORY_DIALOG_NOTES_LENGTH = 100

COMMODITY_DIALOG_MIN_VALUE = 0.0
COMMODITY_DIALOG_MAX_PRICE_VALUE = 1_000.0
COMMODITY_DIALOG_NOTES_LENGTH = 50

CUSTOMERS_DIALOG_NOTES_LENGTH = 200
CUSTOMERS_DIALOG_INDIVIDUAL_INDEX = 0
CUSTOMERS_DIALOG_COMPANY_INDEX = 1

INTEGER_SUFFIXES = ("ks", "pcs")
DECIMAL_SUFFIXES = ("kg",)

PAYMENT_VALUES = ("CASH", "TRANSFER")

SUMMARY_EXPORT_PRICE_MIN_VALUE = 0.0
SUMMARY_BALANCE_PRICE_MIN_VALUE = -99_999_999.9
SUMMARY_EXPORT_PRICE_MAX_VALUE = 99_999_999.9

EXPORT_TYPE_SUMMARY = "summary"
EXPORT_TYPE_TRANSACTIONS = "transactions"

CASH_BALANCE_MIN_VALUE = 0
CASH_BALANCE_MAX_VALUE = 99_999_999
CASH_BALANCE_RESULT_MIN_VALUE = -99_999_999
